version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: churn-frontend
    ports:
      - "8501:8501"
    environment:
      - CHURN_API_URL=http://api:8000
    depends_on:
      - api
